---
- name: Install workstation software
  hosts: localhost
  vars_files:
    - package_list.yaml
  collections:
    - name: community.general
  tasks:
    - name: Install system packages
      # become_user: root
      ansible.builtin.dnf:
        name: "{{item}}"
        state: latest
        update_cache: true
      loop: "{{system_packages}}"
      become: true

    - name: Autoremove unneeded packages installed as dependencies
      ansible.builtin.dnf:
        autoremove: yes
      become: true

    # - name: Install flatpak packages
    #   community.general.flatpak_remote:
    #     name: "{{item}}"
    #     state: present
    #   loop: "{{flatpak_packages}}"

    # - name: Install cargo packages
    #   community.general.cargo:
    #     name: "{{item}}"
    #   loop: "{{cargo_packages}}"

    - name: Install pip packages
      ansible.builtin.pip:
        name: "{{item}}"
      loop: "{{pip_packages}}"
...
